"""initial schema

Revision ID: d08c9fa3ef24
Revises: 
Create Date: 2026-07-22 08:56:22.118135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd08c9fa3ef24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=256), nullable=True),
    sa.Column('app_name', sa.String(length=256), nullable=True),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('version_code', sa.String(length=64), nullable=True),
    sa.Column('min_sdk', sa.String(length=16), nullable=True),
    sa.Column('target_sdk', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('storage_dir', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_md5'), ['md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_package_name'), ['package_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_status'), ['status'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('signature_algorithm', sa.String(length=128), nullable=True),
    sa.Column('sha1', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.String(length=128), nullable=True),
    sa.Column('valid_from', sa.String(length=64), nullable=True),
    sa.Column('valid_to', sa.String(length=64), nullable=True),
    sa.Column('scheme_v1', sa.Boolean(), nullable=True),
    sa.Column('scheme_v2', sa.Boolean(), nullable=True),
    sa.Column('scheme_v3', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('permission', sa.String(length=512), nullable=True),
    sa.Column('authorities', sa.String(length=512), nullable=True),
    sa.Column('grant_uri_permissions', sa.Boolean(), nullable=True),
    sa.Column('intent_filters', sa.Text(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_components_analysis_kind', ['analysis_id', 'kind'], unique=False)

    op.create_table('decompiled_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('tree', sa.String(length=32), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('ext', sa.String(length=32), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('is_text', sa.Boolean(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'rel_path', name='uq_file_path')
    )
    with op.batch_alter_table('decompiled_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decompiled_files_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decompiled_files_ext'), ['ext'], unique=False)
        batch_op.create_index(batch_op.f('ix_decompiled_files_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_decompiled_files_tree'), ['tree'], unique=False)
        batch_op.create_index('ix_files_analysis_tree', ['analysis_id', 'tree'], unique=False)

    op.create_table('firebase_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firebase_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firebase_refs_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('malware_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('indicator', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('malware_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_malware_findings_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('package_name', sa.String(length=256), nullable=True),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('version_code', sa.String(length=64), nullable=True),
    sa.Column('min_sdk', sa.String(length=16), nullable=True),
    sa.Column('target_sdk', sa.String(length=16), nullable=True),
    sa.Column('compile_sdk', sa.String(length=16), nullable=True),
    sa.Column('debuggable', sa.Boolean(), nullable=False),
    sa.Column('allow_backup', sa.Boolean(), nullable=False),
    sa.Column('uses_cleartext_traffic', sa.Boolean(), nullable=True),
    sa.Column('network_security_config', sa.String(length=512), nullable=True),
    sa.Column('manifest_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manifests_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('protection_level', sa.String(length=64), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('sbom_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('purl', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sbom_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbom_components_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sbom_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbom_components_analysis_id'))

    op.drop_table('sbom_components')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_analysis_id'))

    op.drop_table('reports')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_analysis_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manifests_analysis_id'))

    op.drop_table('manifests')
    with op.batch_alter_table('malware_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_malware_findings_analysis_id'))

    op.drop_table('malware_findings')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_analysis_id'))

    op.drop_table('libraries')
    with op.batch_alter_table('firebase_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firebase_refs_analysis_id'))

    op.drop_table('firebase_refs')
    with op.batch_alter_table('decompiled_files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_analysis_tree')
        batch_op.drop_index(batch_op.f('ix_decompiled_files_tree'))
        batch_op.drop_index(batch_op.f('ix_decompiled_files_name'))
        batch_op.drop_index(batch_op.f('ix_decompiled_files_ext'))
        batch_op.drop_index(batch_op.f('ix_decompiled_files_analysis_id'))

    op.drop_table('decompiled_files')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index('ix_components_analysis_kind')
        batch_op.drop_index(batch_op.f('ix_components_analysis_id'))

    op.drop_table('components')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_analysis_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_analyses_sha256'))
        batch_op.drop_index(batch_op.f('ix_analyses_package_name'))
        batch_op.drop_index(batch_op.f('ix_analyses_md5'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
